In [1]:
import pandas as pd
import numpy as np

In [2]:
df_feb = pd.read_csv('data/feb-inter.csv')
df_mar = pd.read_csv('data/march-inter.csv')

# Unimos estos datasets con los que incluyen los casos confirmados a día de hoy y la población
df_feb2 = pd.read_csv('data/feb2.csv')
df_mar2 = pd.read_csv('data/march2.csv')

df_feb = df_feb.merge(df_feb2)
df_mar = df_mar.merge(df_mar2)

df = pd.concat([df_feb,df_mar],ignore_index=True)
# Creamos una estimación de casos entrantes desde un cierto país a otro cada día
df['CasesEstimation'] = np.divide(np.multiply(df['NumPassengers'],df['OriginConfirmed'], dtype=np.double),
                                  df['OriginPopulation'], dtype=np.double)
df.head()

,Zone,Date,ConfirmedCasesWeekLater,Origin,NumPassengers,OriginConfirmed,OriginPopulation,ImportedRisk,Population,ConfirmedCases,CasesEstimation
0,Albania,2020-02-01,0,Greece,121.950,0,10423056,0.000000,2877800,0,0.000000
1,Albania,2020-02-01,0,Hungary,121.950,0,9660350,0.000000,2877800,0,0.000000
2,Albania,2020-02-01,0,Italy,1674.780,2,60461828,0.000056,2877800,0,0.000055
3,Albania,2020-02-01,0,Serbia,127.062,0,8737370,0.000000,2877800,0,0.000000
4,Albania,2020-02-01,0,United Kingdom,100.812,2,67886004,0.000003,2877800,0,0.000003

In [3]:
# Agrupamos las estimaciones de contagios entrantes por país de llegada y fecha
new_df = df.groupby(['Zone','Date','ConfirmedCasesWeekLater','ConfirmedCases','Population']).sum()[['CasesEstimation','ImportedRisk']].reset_index()

In [4]:
new_df = new_df[['Zone', 'Date', 'ConfirmedCases','CasesEstimation','ImportedRisk', 'ConfirmedCasesWeekLater','Population']]
new_df.head()

,Zone,Date,ConfirmedCases,CasesEstimation,ImportedRisk,ConfirmedCasesWeekLater,Population
0,Albania,2020-02-01,0,0.000058,0.000059,0,2877800
1,Albania,2020-02-02,0,0.000086,0.000086,0,2877800
2,Albania,2020-02-03,0,0.000059,0.000059,0,2877800
3,Albania,2020-02-04,0,0.000065,0.000065,0,2877800
4,Albania,2020-02-05,0,0.000033,0.000034,0,2877800

In [5]:
new_df.to_csv('data/inter.csv')